# The Docker image that will be used to build your app
image: node:lts
# Functions that should be executed before the build script is run
stages:
  - build

build:
  stage: build
  script:
    - cd subscribers
    - npm ci
    - npm run build
    - cd example
    - npm ci
    - npm run build
